# This file was generated by GoReleaser. DO NOT EDIT.
cask "webwait" do
  desc ""
  homepage ""
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "webwait"

  on_macos do
    url "https://github.com/supcik/webwait/releases/download/v0.1.5/webwait_Darwin_all.tar.gz"
    sha256 "76ecdf5e880dd2908ae679b1873ea9fd9545009187f651d6a12ee90ec7c75d27"
  end

  on_linux do
    on_intel do
      url "https://github.com/supcik/webwait/releases/download/v0.1.5/webwait_Linux_x86_64.tar.gz"
      sha256 "2216486da41053629a31cd7c4be9cb7da63cf72ee66f7dba949ad34a8638e283"
    end
    on_arm do
      url "https://github.com/supcik/webwait/releases/download/v0.1.5/webwait_Linux_arm64.tar.gz"
      sha256 "d168ca7e20e2ef2f09e1a268b856b7c29a7b32f00939bb6ef417d1721c77a3d5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/foo"]
    end
  end

  # No zap stanza required
end
