# This file was generated by GoReleaser. DO NOT EDIT.
cask "webwait" do
  desc ""
  homepage ""
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "webwait"

  on_macos do
    on_intel do
      url "https://github.com/supcik/webwait/releases/download/v1.0.0/webwait_Darwin_x86_64.tar.gz"
      sha256 "8cea37190be1c5369bf949eb8197229900c00356e39850e60c86bdaf63cb254e"
    end
    on_arm do
      url "https://github.com/supcik/webwait/releases/download/v1.0.0/webwait_Darwin_arm64.tar.gz"
      sha256 "7db56408b420adfca8b2bacfaac385566258c72a3502f4e75c88778e191d2ab6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/supcik/webwait/releases/download/v1.0.0/webwait_Linux_x86_64.tar.gz"
      sha256 "50fb97cb6de8a9fa752396ce9d704dcc6bf67ef79e0e52d5630d57431f0ac1d3"
    end
    on_arm do
      url "https://github.com/supcik/webwait/releases/download/v1.0.0/webwait_Linux_arm64.tar.gz"
      sha256 "d1712e72785013e772bdb25508af680708530a27a2c534d87f9a72d3119856dc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/webwait"]
    end
  end

  # No zap stanza required
end
