# This file was generated by GoReleaser. DO NOT EDIT.
cask "zipserve" do
  name "zipserve"
  desc "HTTP server that serves web content directly from ZIP archives"
  homepage "https://github.com/supcik/zipserve"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zipserve"

  on_macos do
    on_intel do
      url "https://github.com/supcik/zipserve/releases/download/v#{version}/zipserve_Darwin_x86_64.tar.gz"
      sha256 "5bd34677ac5ca6fa359d6fd9a47338ad82acbaadece33e013e829b7a12a9d236"
    end
    on_arm do
      url "https://github.com/supcik/zipserve/releases/download/v#{version}/zipserve_Darwin_arm64.tar.gz"
      sha256 "b2858fa90b01be681cdc0bc4d37d6b689fc90e280cd8b3d9d41c7ef58020e62d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/supcik/zipserve/releases/download/v#{version}/zipserve_Linux_x86_64.tar.gz"
      sha256 "26a06f7d1f18961298c0573c529309ea49f4344c65e5e43be8870d85898ec053"
    end
    on_arm do
      url "https://github.com/supcik/zipserve/releases/download/v#{version}/zipserve_Linux_arm64.tar.gz"
      sha256 "3a3a5d8daf8b38c6cd5b8ad59467d0b042a549f90e328c08058a6e0cee1e2202"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zipserve"]
    end
  end

  # No zap stanza required
end
