# This file was generated by GoReleaser. DO NOT EDIT.
cask "zipserve" do
  name "zipserve"
  desc "HTTP server that serves web content directly from ZIP archives"
  homepage "https://github.com/supcik/zipserve"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zipserve"

  on_macos do
    on_intel do
      url "https://github.com/supcik/zipserve/releases/download/v#{version}/zipserve_Darwin_x86_64.tar.gz"
      sha256 "2e1a89075e66c92e21397552c5d7c2cc181c6a78c9544b50f40b059e83651267"
    end
    on_arm do
      url "https://github.com/supcik/zipserve/releases/download/v#{version}/zipserve_Darwin_arm64.tar.gz"
      sha256 "636fc23bcc9ec811d68841820317d972b19936dfd7e4b4cb0d025e7d93ed8e16"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/supcik/zipserve/releases/download/v#{version}/zipserve_Linux_x86_64.tar.gz"
      sha256 "817551013e45c4b40ea4f6bc17513648f4bd6f959f6be5d77ca0cf21b0342d34"
    end
    on_arm do
      url "https://github.com/supcik/zipserve/releases/download/v#{version}/zipserve_Linux_arm64.tar.gz"
      sha256 "bdea63c9e82452e3cbd8c09f9646c74d9e243380617ddfea9cbaf5a8cfeb022f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zipserve"]
    end
  end

  # No zap stanza required
end
