# This file was generated by GoReleaser. DO NOT EDIT.
cask "zipserve" do
  name "zipserve"
  desc "HTTP server that serves web content directly from ZIP archives"
  homepage "https://github.com/supcik/zipserve"
  version "0.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zipserve"

  on_macos do
    on_intel do
      url "https://github.com/supcik/zipserve/releases/download/v#{version}/zipserve_Darwin_x86_64.tar.gz"
      sha256 "6bedc6c9811ea93a29410397b6035132bb029bcb3795df6baaadff45c1563fe7"
    end
    on_arm do
      url "https://github.com/supcik/zipserve/releases/download/v#{version}/zipserve_Darwin_arm64.tar.gz"
      sha256 "fedc5647b7fae9216868d551c3444dcdba57129975d28ab1e53fe4582b4b8080"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/supcik/zipserve/releases/download/v#{version}/zipserve_Linux_x86_64.tar.gz"
      sha256 "08e3284ab4ff8bab46b65bbc8431a83514575809ad979bae2c1b772cd3fb5e60"
    end
    on_arm do
      url "https://github.com/supcik/zipserve/releases/download/v#{version}/zipserve_Linux_arm64.tar.gz"
      sha256 "f1710086daf1ab3638ef76afff300f6309388ba7688cfbe4e5913be66803ade6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zipserve"]
    end
  end

  # No zap stanza required
end
